Deterministically find module script path and pass along

diff --git a/.azuredevops/multinode-ci-slurm-nightly.yml b/.azuredevops/multinode-ci-slurm-nightly.yml
--- a/.azuredevops/multinode-ci-slurm-nightly.yml
+++ b/.azuredevops/multinode-ci-slurm-nightly.yml
@@ -45,8 +45,17 @@ jobs:
     inputs:
       targetType: inline
       script: |
+        MODULES_INIT_SCRIPT_PATH=$(bash -lc 'echo $MODULESHOME/init/bash')
+
+        if [[ ! -f "$MODULES_INIT_SCRIPT_PATH" ]]; then
+          echo "ERROR: Modules init script not found at $MODULES_INIT_SCRIPT_PATH"
+          exit 1
+        fi
+
+        echo "Modules init script found at $MODULES_INIT_SCRIPT_PATH"
+
         echo "Submitting build job..."
-        BUILD_JOB_ID=$(sbatch --export=ALL --parsable $(Build.SourcesDirectory)/.azuredevops/slurm/build.sh)
+        BUILD_JOB_ID=$(sbatch --export=MODULES_INIT_SCRIPT=$MODULES_INIT_SCRIPT_PATH --parsable $(Build.SourcesDirectory)/.azuredevops/slurm/build.sh)
         echo "Submitted build job: $BUILD_JOB_ID"
         echo "##vso[task.setvariable variable=BUILD_JOB_ID]$BUILD_JOB_ID"
 
@@ -94,8 +103,17 @@ jobs:
     inputs:
       targetType: inline
       script: |
+        MODULES_INIT_SCRIPT_PATH=$(bash -lc 'echo $MODULESHOME/init/bash')
+
+        if [[ ! -f "$MODULES_INIT_SCRIPT_PATH" ]]; then
+          echo "ERROR: Modules init script not found at $MODULES_INIT_SCRIPT_PATH"
+          exit 1
+        fi
+
+        echo "Modules init script found at $MODULES_INIT_SCRIPT_PATH"
+
         echo "Submitting test job..."
-        TEST_JOB_ID=$(sbatch --export=ALL --parsable $(Build.SourcesDirectory)/.azuredevops/slurm/test.sh)
+        TEST_JOB_ID=$(sbatch --export=MODULES_INIT_SCRIPT=$MODULES_INIT_SCRIPT_PATH --parsable $(Build.SourcesDirectory)/.azuredevops/slurm/test.sh)
         echo "Submitted test job: $TEST_JOB_ID"
         echo "##vso[task.setvariable variable=TEST_JOB_ID]$TEST_JOB_ID"
 
